name: RDP

on:
  workflow_dispatch:

jobs:
  windows-rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Enable RDP
      run: |
        Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
        net user github P@ssword123!
        net localgroup administrators github /add
    - name: Display Connection Info
      run: |
        Write-Host "RDP is now enabled"
        ipconfig
        Write-Host "Username: github"
        Write-Host "Password: P@ssword123!"
        Start-Sleep -Seconds 21600
